name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Print system info
      run: uname -m
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: macos-latest-on-RelWithDebInfo
    - uses: turtlesec-no/get-ninja@main
    - name: Generating Makefiles
      shell: bash
      run: |
        curl -L https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-macOS-Release-x64.zip --output skia.zip
        unzip skia.zip -d skia
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
          -DENABLE_TESTS=ON \
          -DENABLE_UI=ON \
          -DENABLE_CCACHE=ON \
          -DLAF_BACKEND=skia \
          -DSKIA_DIR=./skia \
          -DSKIA_LIBRARY_DIR=./skia/out/Release-x64 \
          -DSKIA_LIBRARY=./skia/out/Release-x64/libskia.a
    - name: Compiling
      shell: bash
      run: |
        cd build && ninja
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: aseprite
        path: build/*
